- name: Get latest Node Exporter version
  shell: |
    curl -s https://api.github.com/repos/prometheus/node_exporter/releases/latest \
    | grep tag_name | cut -d '"' -f4
  register: node_exporter_version
  changed_when: false

- name: Set version without "v"
  set_fact:
    node_exporter_ver: "{{ node_exporter_version.stdout | regex_replace('^v', '') }}"

- name: Download Node Exporter
  get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_ver }}/node_exporter-{{ node_exporter_ver }}.linux-amd64.tar.gz"
    dest: /tmp/node_exporter.tar.gz
    mode: '0644'

- name: Extract Node Exporter
  unarchive:
    src: /tmp/node_exporter.tar.gz
    dest: /usr/local/bin/
    remote_src: yes
    creates: "/usr/local/bin/node_exporter-{{ node_exporter_ver }}.linux-amd64"

- name: Create Node Exporter symlink
  file:
    src: "/usr/local/bin/node_exporter-{{ node_exporter_ver }}.linux-amd64"
    dest: /usr/local/bin/node_exporter
    state: link
    force: yes

- name: Ensure node_exporter binary is executable
  file:
    path: /usr/local/bin/node_exporter/node_exporter
    mode: '0755'

- name: Deploy systemd service
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
  notify: restart node_exporter

- name: Reload systemd
  systemd:
    daemon_reload: yes 

- name: Enable and start Node Exporter
  systemd:
    name: node_exporter
    enabled: yes
    state: started
