---
- name: Download mysql_exporter
  get_url:
    url: https://github.com/prometheus/mysqld_exporter/releases/download/v{{ mysql_exporter_version }}/mysqld_exporter-{{ mysql_exporter_version }}.linux-amd64.tar.gz
    dest: /tmp/

- name: Extract mysql_exporter
  unarchive:
    src: /tmp/mysqld_exporter-{{ mysql_exporter_version }}.linux-amd64.tar.gz
    dest: /tmp/
    remote_src: yes

- name: Install mysql_exporter binary
  copy:
    src: /tmp/mysqld_exporter-{{ mysql_exporter_version }}.linux-amd64/mysqld_exporter
    dest: /opt/mysqld_exporter
    mode: '0755'
    remote_src: yes

- name: Create config directory
  file:
    path: /etc/mysql_exporter
    state: directory
    owner: root
    mode: '0750'

- name: Deploy MySQL exporter config
  template:
    src: my.cnf.j2
    dest: /etc/mysql_exporter/.my.cnf
    owner: root
    mode: '0600'
  notify: restart mysql_exporter

- name: Install systemd service
  template:
    src: mysql_exporter.service.j2
    dest: /etc/systemd/system/mysql_exporter.service
  notify: restart mysql_exporter

- name: Enable and start mysql_exporter
  systemd:
    name: mysql_exporter
    enabled: yes
    state: started
    daemon_reload: yes

