---
- name: Setup monitoring stack
  hosts: prometheus
  become: yes
  roles:
    - loki
    # - alertmanager
    # - prometheus
    # - grafana

# - name: Install data exporter on agents
#   hosts: prometheus_agents
#   become: yes
#   roles:
#     - exporters/blackbox_exporter
#     - exporters/node_exporter 
#     - exporters/mysql_exporter

